/**
 * /manifest.webmanifest — generated by Next.js MetadataRoute.Manifest.
 *
 * PWA install metadata. Even without offline / service-worker support, this
 * is what tells iOS / Android what name + icon to use when "Add to Home
 * Screen". Theme color matches the moss primary so the standalone splash
 * background isn't white.
 */

import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Pannly",
    short_name: "Pannly",
    description:
      "Find an idea worth building. Get refunded if you actually ship.",
    start_url: "/",
    display: "standalone",
    background_color: "#faf9f7",
    theme_color: "#2a4c3f",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
